config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :restaurants do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews

  validates :zip_code, numericality: true
  validates :name, :address, :city, :state, :zip_code, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :rating, numericality: true
  validates :rating, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  validates :rating, :body, :restaurant_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show

    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews

    @review = Review.new

  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant}
      else
        format.html { render action: 'new' }
      end
    end

  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end

  end

  def destroy

    @restaurant = Restaurant.find(params[:id])

    @restaurant.destroy

    redirect_to restaurants_path

  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state, :zip_code, :description, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build()
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @restaurant}
      else
        format.html { render action: 'new' }
      end
    end
  end

  private
  def review_params
    params.require(:review).permit(:rating, :body, :restaurant_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @restaurants = Restaurant.order("created_at desc").limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit a Restaurant</h1>

<%= form_for @restaurant do |f| %>

  <% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited
      this restaurant from being posted:</h2>
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
  <%= f.label :name %>:
  <%= f.text_field :name %>
  </p>

  <p>
  <%= f.label :address %>:
  <%= f.text_field :address %>
  </p>

  <p>
  <%= f.label :city %>:
  <%= f.text_field :city %>

  <%= f.label :state %>:
  <%= f.text_field :state %>

  <%= f.label :zip_code %>:
  <%= f.text_field :zip_code %>
  </p>

  <p>
  <%= f.label :category %>:
  <%= f.text_field :category %>
  </p>

  <p>
  <%= f.label :description %>:<br />
  <%= f.text_area :description, size: "60x12" %>
  </p>

  <p>
  <%= f.submit "Submit" %>
  </p>
<% end %>

<br />
<%= link_to 'Back', @restaurant %>
<br />

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>

</ul>

<p><%= link_to "Add a Restaurant", new_restaurant_path %></p>

<p><%= link_to "Home", root_path %></p>

app/views/restaurants/new.html.erb
<h1>Add a Restaurant</h1>

<%= form_for @restaurant, url: {action: "create"} do |f| %>

  <% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited
      this restaurant from being posted:</h2>
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
  <%= f.label :name %>:
  <%= f.text_field :name %>
  </p>

  <p>
  <%= f.label :address %>:
  <%= f.text_field :address %>
  </p>

  <p>
  <%= f.label :city %>:
  <%= f.text_field :city %>

  <%= f.label :state %>:
  <%= f.text_field :state %>

  <%= f.label :zip_code %>:
  <%= f.text_field :zip_code %>
  </p>

  <p>
  <%= f.label :category %>:
  <%= f.text_field :category %>
  </p>

  <p>
  <%= f.label :description %>:<br />
  <%= f.text_area :description, size: "60x12" %>
  </p>

  <p>
  <%= f.submit "Create" %>
  </p>
<% end %>

<br />
<%= link_to 'Back', restaurants_path %>
<br />

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= @restaurant.address %> <%= @restaurant.city %>, <%= @restaurant.state %> <%= @restaurant.zip_code %></p>

<h4><%= @restaurant.description %></h4>

<p><%= link_to "Edit", edit_restaurant_path %> <%= link_to 'Delete', @restaurant,
            method: :delete,
            data: { confirm: 'Are you sure?' } %></p>


<h3>Reviews</h3>

  <ul>
    <% @reviews.each do |review| %>
    <li>
    <h3><%= review.rating %> (of 5) Stars</h3>
    <%= review.body %>
    </li>
    <%end%>
  </ul>

<p><%= link_to "Review #{@restaurant.name}", new_restaurant_review_path(@restaurant) %></p>

<p><%= link_to "Back", restaurants_path %></p>

app/views/reviews/new.html.erb
<h3>Review <%= @restaurant.name %></h3>

<%= form_for [@restaurant, @review], url: {action: "create"} do |f| %>

  <% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited
      this review from being posted:</h2>
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
  <%= f.label :rating %> (1-5): <%= f.text_field :rating %>
  </p>

  <p>
  <%= f.label :review %>:<br />
  <%= f.text_area :body, size: "60x12" %>
  </p>

  <p>
  <%= f.submit "Create" %>
  </p>
<% end %>


<%= link_to "Back", @restaurant %>
<br />

app/views/welcome/index.html.erb
<h1>Welcome to Good Eats</h1>

<h2>Recently Added</h2>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>

</ul>

<%= link_to "All Restaurants", restaurants_path %>